project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: true
lang: es
cover-image: cover.png
book:
  title: "R para Microbiología Industrial: Análisis de Datos y Diseño Experimental con un Enfoque Práctico"
  author:
    - "Fredy Ortiz"
    - "Miguel Pérez"
    - "Francisco León"
  date: "2025-05-05"
  # GitHub
  site-url: "https://udesanalitica.github.io/r-para-mi/"
  repo-url: "https://github.com/udesanalitica/r-para-mi"
  repo-branch: main
  repo-actions: [edit, issue, source]
  favicon: favicon.png
  page-navigation: true
  search: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - autores.qmd
    - agradecimientos.qmd
    - intro.qmd
    - Chapter_01.qmd
    - Chapter_02.qmd
    - Chapter_03.qmd
    - Chapter_04.qmd
    - Chapter_05.qmd
    - Chapter_06.qmd
    - references.qmd
bibliography: references.bib
csl: apa.csl
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-copy: true
    smooth-scroll: true
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex   # ← OPCIONAL pero recomendable
  docx:
    toc: true
    number-sections: false
  epub:
    cover-image: cover.png
website:
  page-footer:
    left: "© 2025 Autores"
    right: "Publicado con Quarto y GitHub Pages"
execute:
  freeze: auto
editor: visual