project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    browser: true

lang: es
cover-image: cover.png

book:
  title: "R para Microbiolog칤a Industrial: An치lisis de Datos y Dise침o Experimental con un Enfoque Pr치ctico"
  author:
    - "Fredy Ortiz"
    - "Miguel P칠rez"
    - "Francisco Le칩n"
  date: "2025-05-05"

  # GitHub
  site-url: "https://udesanalitica.github.io/r-para-mi/"
  repo-url: "https://github.com/udesanalitica/r-para-mi"
  repo-branch: main
  repo-actions: [edit, issue, source]

  favicon: favicon.png
  page-navigation: true
  search: true
  downloads: [pdf, epub]

  chapters:
    - index.qmd
    - autores.qmd
    - agradecimientos.qmd
    - intro.qmd
    - Chapter_01.qmd
    - Chapter_02.qmd
    - Chapter_03.qmd
    - Chapter_04.qmd
    - Chapter_05.qmd
    - Chapter_06.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    code-copy: true
    smooth-scroll: true
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
  epub:
    cover-image: cover.png
    code-copy: true
    mathjax: true   # 游녣 Esto habilita las f칩rmulas matem치ticas

website:
  page-footer:
    left: "춸 2025 Autores"
    right: "Publicado con Quarto y GitHub Pages"

execute:
  freeze: auto

editor: visual